# Note that the local default.yml is overwritten on CodeClimate with the contents of
# the remote rubocop.yml pulled from GitHub in a codeclimate prepare step.
inherit_from:
  - default.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/seeds/**/*"
    - "db/migrate/**/*"
    - "config/initializers/devise.rb"
    - "db/schema.rb"
    - "spec/dummy/db/schema.rb"

Rails/Output:
  Enabled: true
  Exclude:
    - "db/**/*"

# Disabling this as it is not
RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - "spec/system/**/*"

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - "spec/system/**/*"

RSpec/ExampleLength:
  Max: 5
  Exclude:
    - "spec/system/**/*"

Metrics/AbcSize:
  Enabled: true
  Max: 10
  Exclude:
    - "db/**/*"

Metrics/MethodLength:
  Enabled: true
  Max: 10
  Exclude:
    - "db/**/*"

Metrics/AbcSize:
  Enabled: true
  Max: 12
  Exclude:
    - "db/**/*"
